### ISSUE TITLE
Integrate Squareline basic UI

### ISSUE THREAD

**Issue by pixelwave** [zingo/Sunton_ESP32-8048S043#2]
Thanks a lot for this getting startet guide. It works and I can see the demo on my board running! 

Could you maybe support with another version including a basic working Squareline GUI (simple button transition from screen 1 > screen 2) so I can go from there? I tried myself but can not really integrate the UI files in your project.

Maybe also updating the libraries to the latest (got some errors myself when trying to use newer libraries):

lib_deps = 
	moononournation/GFX Library for Arduino@^1.4.0
	lvgl/lvgl@^8.3.9
	tamctec/TAMC_GT911@^1.0.2
	SPI@^2.0.0
	Wire@^2.0.0

**Comment by zingo** [comment]
Hi
I have moved on and not used this in a long while, sorry. I have a much larger project that I hope works better that you could try here: 
https://github.com/zingo/CrazyCapyTime

I see that I have not updated it to GFX Library for Arduino@^1.4.0 it is still on

	lvgl/lvgl@^8.3.0
	moononournation/GFX Library for Arduino@1.3.1
	tamctec/TAMC_GT911@^1.0.2
	
There might have been some problem and I just decided to keep it at 1.3.1 but I don't really remember, sorry

**Comment by pixelwave** [comment]
After more fiddling around I managed to come up with something running! https://github.com/pixelwave/Sunton-ESP32-8048S043

**Comment by zingo** [comment]
Thanks for the update/fix, I have added a link to your project in the README as I probably will not update this in the near future :) 
Great work!
